version: '3.9'
services:

  stockfish:
    image: kayvan/stockfish:latest

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
    volumes:
      - ./postgresql/volume/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - $PORT:$PORT
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
